-- MySQL Script generated by MySQL Workbench
-- Wed Jun  1 17:34:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Viergewinnt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Viergewinnt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Viergewinnt` DEFAULT CHARACTER SET utf8 ;
USE `Viergewinnt` ;

-- -----------------------------------------------------
-- Table `Viergewinnt`.`SpielerLiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viergewinnt`.`SpielerLiga` (
  `idLiga` INT NOT NULL AUTO_INCREMENT,
  `NameSpieler` VARCHAR(45) NOT NULL,
  `Punkte` INT NOT NULL,
  `Siege` INT NOT NULL,
  `Niederlagen` INT NOT NULL,
  `3er` INT NOT NULL,
  `unentschieden` INT NOT NULL,
  PRIMARY KEY (`idLiga`),
  UNIQUE INDEX `idLiga_UNIQUE` (`idLiga` ASC) )
;


-- -----------------------------------------------------
-- Table `Viergewinnt`.`SpieleLiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viergewinnt`.`SpieleLiga` (
  `Liga_idLiga` INT NOT NULL,
  `Liga_idLiga1` INT NOT NULL,
  `gewinner` VARCHAR(45) NULL,
  `unentschieden` TINYINT NOT NULL,
  `Spieler_3er` VARCHAR(45) NOT NULL,
  `Spieler1_3er` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Liga_idLiga`, `Liga_idLiga1`),
  INDEX `fk_Liga_has_Liga_Liga1_idx` (`Liga_idLiga1` ASC) ,
  INDEX `fk_Liga_has_Liga_Liga_idx` (`Liga_idLiga` ASC) ,
  CONSTRAINT `fk_Liga_has_Liga_Liga`
    FOREIGN KEY (`Liga_idLiga`)
    REFERENCES `Viergewinnt`.`SpielerLiga` (`idLiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Liga_has_Liga_Liga1`
    FOREIGN KEY (`Liga_idLiga1`)
    REFERENCES `Viergewinnt`.`SpielerLiga` (`idLiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `Viergewinnt`.`Spiele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viergewinnt`.`Spiele` (
  `idSpiele` INT NOT NULL AUTO_INCREMENT,
  `spieler` VARCHAR(45) NOT NULL,
  `spieler1` VARCHAR(45) NOT NULL,
  `Gewinner` VARCHAR(45) NULL COMMENT 'name of winner ',
  PRIMARY KEY (`idSpiele`),
  UNIQUE INDEX `idSpiele_UNIQUE` (`idSpiele` ASC) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;